def resumo(num, porc, redu):
    print('-'*30)
    print(f'{"RESUMO DO VALOR":^30}')
    print('-'*30)
    print(f'{"Preço analisado:":<20}', end='')
    print(f'R${num:.2f}'.replace('.',','))
    print(f'{"Dobro do preço:":<20}', end='')
    print(f'R${num*2:.2f}'.replace('.',','))
    print(f'{"Metade do preço:":<20}', end='')
    print(f'R${num/2:.2f}'.replace('.',','))
    print(f'{porc}{"% de aumento:":<18}', end='')
    print(f'R${num+((num/100)*porc):.2f}'.replace('.',','))
    print(f'{redu}{"% de redução:":<18}', end='')
    print(f'R${num-((num/100)*redu):.2f}'.replace('.',','))
    print('-'*30)