num = int(input('Digite um numero de 4 digitos: '))
n = str(num)
print(f'Analisando o numero {num}...')
print(f'Unidade:{n[3]}')
print(f'Dezena:{n[2]}')
print(f'Centena:{n[1]}')
print(f'Milhar{n[0]}')